### PR TITLE
Fix broken windows

### PR DESCRIPTION
**Pull request by wavded**
This adds support for Jenkins pipelines. Removes a lot of cruft to make
the code base easier to maintain. Cleans up the members and partners
lists. Cleans up logos and darkens the UI.

screen shot 2018-11-27 at 3 07 39 pm

### CODE REVIEW

**Comment by levifelling** [comment]
@wavded testing this locally and I'm seeing that the map events are different than what is on http://cvhta.com/. Specifically, on LIVE a double click on the map causes the map to become full screen.

**Comment by wavded** [comment]
I removed that ability

**Comment by levifelling** [comment]
Panning map slightly to north gives a bunch of tile requests that return 503 errors.
screen shot 2018-11-27 at 4 00 33 pm

http://b.tile.stamen.com/toner/12/1009/1470@2x.png

**Comment by wavded** [comment]
Yeah I noticed that locally too, not sure why some of those aren't returning.

**Comment by levifelling** [comment]
UI is missing the Navigation links in upper right.

**Comment by wavded** [comment]
Yep, on purpose, I also removed the whole media page. The website is only a page now and those links seemed unnecessary, you can email at the bottom now with the other social media links.

**Comment by wavded** [comment]
Decided to keep what's live on live, don't feel too motivated to undo all that work at this point. We can later revisit if desired.

**Comment by wavded** [comment]
Made a few adjustments:

1. Switched back to stamen-lite (found retina tiles for it)
2. Sorted clients in lists
3. Fixed a few UI display bugs
4. Fixed a missing link for a client

**Comment by levifelling** [comment]
LGTM. Thanks @wavded

**Pull request merged**
